[package]
name = "socket2-libc-align-demo"
version = "0.0.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
socket2 = "=0.3.15"

[package.metadata.raze]
workspace_path = "//cargo"
target = "x86_64-unknown-linux-gnu"
genmode = "Remote"
